language: python
python:
  - 3.8
services:
  - postgresql
install:
  - psql -c 'create database django_db owner postgres;' -U postgres
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py test shop/tests/
deploy:
  provider: heroku
  api_key:
    secure: MJLW4SX/BsuezTNmljZGWLgay+v1gdSpp1JbEu01txgPkh7WJ2lopA+A7q9kLCSx87j6lDBFld2bYv4zDW04NJ9Z4pk6fhIHjJCJwWJKDt+2za6kybq2yNwGxKaLbPWy0LNCYQNtt0n6XkMLrznjmYOhkIE/+GG5arCO4wzH4hjsxOYpPvEEu5Lh8FVjun+6/Lak3DGbs4CufxrvwFwAEDjavKPPv3v1yD/qFahY3YVPoeimjDbrRPC+9OisgWPYAkHeDiyfEVH8PHw802WgG6elrSrl00A8vUgS5rRK1cCvh5EL+B8KkifuCWq8sprYLiI1+T87iV0DpuyFH6lFg2oOoOsSVd69WpvyGdHkQE/mjXWhv0UuFfmoY6bhniKvGQCv55/Bw3O3VGcUYOt2Ys4AxDXGgUBZUelGn8QUEhp2ET0ih5HiwQmHnEU1YNYAOTkMnQbu1+w5KtkfVYX381lZ277pSI21Egqz+NuMfrhOlbtYqTrt4z14mdJYwDVmI6dQel1NkJ5O9Mzmo8f1IVlfgLGSDUENuWp1m9nXqju6o4Zk2gDJeKSzW9VyjK/BK9rVG+eu7CW5IjjNSR7nskk2zQKbo6mmG9+1fSyKll2c4JuDOY1PnxdoRp9NLnRPMZrmKmCZqb8iR6/DMvsKQkfslhCTQ6PNkca0/PKC+p4=
  app: krivabokov-app
  run: python manage.py loaddata products.yaml && python manage.py migrate
  on: master
