# Generated by Django 3.2.8 on 2021-10-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
