# Generated by Django 4.2.6 on 2023-11-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="price",
            field=models.PositiveIntegerField(default=3000),
            preserve_default=False,
        ),
    ]
