# Generated by Django 4.2.6 on 2023-10-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='person',
            field=models.CharField(max_length=255),
        ),
    ]
