# Generated by Django 4.2.6 on 2023-11-13 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_purchase_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="price",
        ),
    ]
