# Generated by Django 4.2.6 on 2023-11-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_remove_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
