# Generated by Django 3.2.8 on 2021-11-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_purchase_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sale_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
