# Generated by Django 4.2.6 on 2023-11-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_purchase_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promokod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promokod", models.CharField(max_length=200)),
                ("discount", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
